version: "3.8"

services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - 3001:3001
    healthcheck:
      # test: ["ping", "database"]
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: pnpm start
    # command: pnpm seed && pnpm start
    environment:
      PORT: 3001
      MONGO_URI: ${MONGO_URI}
      MONGO_URI_TEST: ${MONGO_URI_TEST}
      CLIENT_ENDPOINT: ${CLIENT_ENDPOINT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}

  db:
    image: mongo:4.0.28-rc0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
