version: "3.8"

services:
  server:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 3001:3001
    healthcheck:
      # test: ["ping", "db"]
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: mongo:4.0.28-rc0-xenial
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - vidly:/data/db

volumes:
  vidly:
