version: "3.8"

services:
  server:
    build: .
    image: vidly_server:1
    restart: always
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
    command: pnpm db:up && pm2-runtime process.json

  db:
    image: mongo:4.0.28-rc0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly:
