version: "3.8"

services:
  server:
    build: ./
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    depends_on:
      - db
    healthcheck:
      # test: ["ping", "database"]
      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    # command: pnpm seed && pnpm start
    # command: ./docker-entrypoint.sh
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_URI_TEST: ${MONGO_URI_TEST}
      CLIENT_ENDPOINT: ${CLIENT_ENDPOINT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      # MONGO_URI: mongodb://db/vidly
      # MONGO_URI_TEST: mongodb://db/vidly-test
      # CLIENT_ENDPOINT: http://localhost:3000
      # JWT_PRIVATE_KEY: thisIsmYFucKingjSonWeBtOkenpRivAtEkEY

  db:
    image: mongo:4.0.28-rc0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
