name: CI

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: ${{secrets.JWT_PRIVATE_KEY}}
      # MONGO_URI_TEST: ${{secrets.MONGO_URI_TEST}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: "^16.3.0"
      - uses: actions/cache@v2.1.7
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
      - run: pnpm test

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: AkhileshNS/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
  #         heroku_email: "YOUR EMAIL"
